# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        session_adapter:
            local:
                directory: '%kernel.cache_dir%/../../sessions'

    filesystems:
        sessions:
            adapter: session_adapter
            alias: League\Flysystem\Filesystem
