security:
    encoders:
        App\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    
    role_hierarchy:
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN]
        ROLE_ADMIN: ROLE_USER

    providers:
        adriver_oauth:
            id: App\Security\Provider\AuthJwtUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        docs:
            pattern: ^/docs
            security: false

        app_version:
            pattern: ^/state$
            security: false

        # main:
        #     pattern: ^/
        #     provider: adriver_oauth
        #     stateless: true
        #     guard:
        #         authenticators:
        #             - App\Security\Authenticator\JwtGuardAuthenticator
    access_control:
        # - { path: ^/, roles: ROLE_USER }
