api_platform:
    enable_swagger_ui: true
    enable_docs: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        html:     ['text/html']
