services:
    _defaults:
        autowire: true
        autoconfigure: true 
        bind:
            $appVersion: '%env(APP_VERSION)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    monolog.formatter.json:
        alias: 'App\Logger\Formatter\JsonFormatter'
        
    ElevenLabs\Api\Factory\SwaggerSchemaFactory: ~

    App\Swagger\LoginCheckDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\LoginCheckDecorator.inner' ]
        autoconfigure: false